version: '3.5'
services:
# ----------------------------------------------
  tracker1:
    image: hehety/godfs:1.0.4-beta
    command: tracker
    environment:
      - port=1022
    volumes:
      - tracker1:/godfs/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == tracker
    networks:
      - host

  tracker2:
    image: hehety/godfs:1.0.4-beta
    command: tracker
    environment:
      - port=1023
    volumes:
      - tracker2:/godfs/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == tracker
    networks:
      - host

# ----------------------------------------------

  storage1:
    image: hehety/godfs:1.0.4-beta
    command: storage
    environment:
      - port=1024
      - http_port=8001
      - group=G01
      - trackers=192.168.1.141:1022
    volumes:
      - storage1:/godfs/data
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.role == storage
    networks:
      - host


  storage2:
    image: hehety/godfs:1.0.4-beta
    command: storage
    environment:
      - port=1025
      - http_port=8002
      - group=G02
      - trackers=192.168.1.141:1023
    volumes:
      - storage2:/godfs/data
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.role == storage
    networks:
      - host


# ----------------------------------------------
  gateway:
    image: nginx
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == tracker
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - host

# ----------------------------------------------


networks:
  host:
    external: true

volumes:
  tracker1:
  tracker2:
  storage1:
  storage2:


