version: '3.5'
services:
# ----------------------------------------------
  tracker1:
    image: hehety/godfs:1.0.6-beta
    command: tracker
    ports:
      - "1022:1022"
    environment:
      - port=1022
#    volumes:
#      - tracker1:/godfs/data
    networks:
      - godfs

  tracker2:
    image: hehety/godfs:1.0.6-beta
    command: tracker
    ports:
      - "1023:1023"
    environment:
      - port=1023
#    volumes:
#      - tracker2:/godfs/data
    networks:
      - godfs

# ----------------------------------------------

  storage1:
    image: hehety/godfs:1.0.6-beta
    command: storage
    deploy:
      mode: global
    environment:
      - port=1024
      - http_port=8001
      - group=G01
      # replace this address by your proxy server
      - advertise_addr=${PROXY_HOST}
      - advertise_port=2024
      - trackers=tracker1:1022,tracker2:1023
#    volumes:
#      - storage1:/godfs/data
    networks:
      - godfs


  storage2:
    image: hehety/godfs:1.0.6-beta
    command: storage
    deploy:
      mode: global
    environment:
      - port=1025
      - http_port=8002
      - group=G02
      # replace this address by your proxy server
      - advertise_addr=${PROXY_HOST}
      - advertise_port=2025
      - trackers=tracker1:1022,tracker2:1023
#    volumes:
#      - storage2:/godfs/data
    networks:
      - godfs


# ----------------------------------------------
  gateway:
    image: hehety/nginx
    ports:
      - "80:80"
      - "2024:2024"
      - "2025:2025"
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
    networks:
      - godfs


# ----------------------------------------------
networks:
  godfs:
    driver: overlay

