version: '3.5'
services:
# ----------------------------------------------
  tracker1:
    image: hehety/godfs:1.0.5-beta
    command: tracker
    environment:
      - port=1022
#    volumes:
#      - tracker1:/godfs/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == tracker
    networks:
      - godfs

  tracker2:
    image: hehety/godfs:1.0.5-beta
    command: tracker
    environment:
      - port=1023
#    volumes:
#      - tracker2:/godfs/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == tracker
    networks:
      - godfs

# ----------------------------------------------

  storage_group1:
    image: hehety/godfs:1.0.5-beta
    command: storage
    environment:
      - port=1024
      - http_port=8001
      - group=G01
      - advertise_port=2033
      # replace this address by your proxy server
      - advertise_addr=192.168.1.187
      - trackers=tracker1:1022,tracker2:1023
#    volumes:
#      - storage1:/godfs/data
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.role == storage
    networks:
      - godfs


  storage_group2:
    image: hehety/godfs:1.0.5-beta
    command: storage
    environment:
      - port=1025
      - http_port=8002
      - group=G02
      - advertise_port=2034
      # replace this address by your proxy server
      - advertise_addr=192.168.1.187
      - trackers=tracker1:1022,tracker2:1023
#    volumes:
#      - storage2:/godfs/data
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.role == storage
    networks:
      - godfs


# ----------------------------------------------
  gateway:
    image: nginx
    ports:
      - "80:80"
      - "2033:2033"
      - "2034:2034"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == tracker
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - godfs

# ----------------------------------------------


networks:
  godfs:
    driver: overlay

