version: '3.5'
services:
# ----------------------------------------------
  tracker1:
    image: hehety/godfs:1.0.5-beta
    command: tracker
    environment:
      - port=1022
#    volumes:
#      - tracker1:/godfs/data
    networks:
      - godfs

  tracker2:
    image: hehety/godfs:1.0.5-beta
    command: tracker
    environment:
      - port=1023
#    volumes:
#      - tracker2:/godfs/data
    networks:
      - godfs

# ----------------------------------------------

  storage_group1:
    image: hehety/godfs:1.0.5-beta
    command: storage
    environment:
      - port=1024
      - http_port=8001
      - group=G01
      - advertise_port=2033
      # replace this address by your proxy server
      - advertise_addr=192.168.0.105
      - trackers=tracker1:1022,tracker2:1023
#    volumes:
#      - storage1:/godfs/data
    networks:
      - godfs


  storage_group2:
    image: hehety/godfs:1.0.5-beta
    command: storage
    environment:
      - port=1025
      - http_port=8002
      - group=G02
      - advertise_port=2034
      # replace this address by your proxy server
      - advertise_addr=192.168.0.105
      - trackers=tracker1:1022,tracker2:1023
#    volumes:
#      - storage2:/godfs/data
    networks:
      - godfs


# ----------------------------------------------
  gateway:
    image: hehety/nginx
    ports:
      - "80:80"
      - "2033:2033"
      - "2034:2034"
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
    networks:
      - godfs

# ----------------------------------------------


networks:
  godfs:
    driver: overlay

