version: '3.0'
services:
  tracker1:
    image: hehety/godfs:1.0.3-beta
    command: tracker
    ports:
      - "1022:1022"
    environment:
      - port=1022
    networks:
      - godfs

  storage1:
    image: hehety/godfs:1.0.3-beta
    command: storage
    ports:
      - "1024:1024"
      - "8001:8001"
    environment:
      - port=1024
      - http_port=8001
      - instance_id=01
      - advertise_addr=ssh.xxx.com
      - trackers=tracker1:1022
    networks:
      - godfs

  storage2:
    image: hehety/godfs:1.0.3-beta
    command: storage
    ports:
      - "1025:1025"
      - "8002:8002"
    environment:
      - port=1025
      - http_port=8002
      - instance_id=02
      - advertise_addr=ssh.xxx.com
      - trackers=tracker1:1022
    networks:
      - godfs

networks:
  godfs:
    driver: overlay